language: python

python:
    - "2.6"
    - "2.7"

env:
  - NEURODEBIAN=0
  - NEURODEBIAN=1

before_install:
    - deactivate
    - wget -O- http://neuro.debian.net/lists/precise.us-nh.libre | sudo tee /etc/apt/sources.list.d/neurodebian.sources.list
    - sudo apt-key adv --recv-keys --keyserver pgp.mit.edu 2649A5A9
    - if [ $NEURODEBIAN -eq 1 ]; then sudo apt-get update -qq; fi
    - sudo apt-get install -qq python-scipy python-nose python-nibabel python-sklearn
    - virtualenv --system-site-packages ~/virtualenv/this
    - source ~/virtualenv/this/bin/activate

install:
    - python setup.py install

script:
    - make clean
    - make test-code
